
@address = http://localhost:5122

###
GET {{address}}/testJson

###
POST {{address}}/sendMessage
Content-Type: application/json

{
    "Author":"TomaszKrasienko",
    "Content":"Test",
    "CreationDate":"2023-10-28"
}