version: '3'

services:
  rabbitmq1:
    image: rabbitmq:management
    container_name: rabbitmq1
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"